FROM node:18-alpine

# Set the working directory inside the container
WORKDIR /app/backend

# Copy package.json and package-lock.json to the working directory
COPY ./backend/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the backend source code
COPY ./backend/ .

# Expose the port 
EXPOSE 3000

# Command to run the application 
CMD ["node", "server.js"]