version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: mern_backend
    restart: always
    ports:
      - "5000:3000"
    volumes:
      - ./backend:/app/backend # It creates a bind mount
    networks:
      - todo-network
    environment:
      - MONGO_URI=${MONGO_URI}
    command: ["npm", "run", "dev"]
    depends_on:
      - mongo

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: mern_frontend
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app/frontend # It creates a bind mount
    networks:
      - todo-network
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    container_name: mern_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - todo-network

volumes:
  mongo-data:
networks:
  todo-network:
